function [fitresult, xData, yData] = createFit(data)
%CREATEFIT(DAILY_CONFIRMED_GROWTH)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: daily_confirmed_growth
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Apr-2020 22:49:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], data );

% Set up fittype and options.
ft = fittype( 'poly9' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

